// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	graph "github.com/pjimming/baize/baize/internal/handler/graph"
	"github.com/pjimming/baize/baize/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/baize/v1/gengerate-graph",
				Handler: graph.GenerateGraphHandler(serverCtx),
			},
		},
	)
}
