// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	local "github.com/pjimming/baize/core/internal/handler/local"
	"github.com/pjimming/baize/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/baize/v1/local/module/path",
				Handler: local.GetModulePathHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/baize/v1/local/packages",
				Handler: local.GetPackagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/baize/v1/local/module/name",
				Handler: local.GetModuleNameHandler(serverCtx),
			},
		},
	)
}
