// Code generated by goctl. DO NOT EDIT.
package types

type CommonDirReq struct {
	Dir string `form:"dir"`
}

type CommonModulePathReq struct {
	ModulePath string `form:"modulePath"`
}

type GetModuleInfoResp struct {
	ModulePath    string `json:"modulePath"`
	ModuleName    string `json:"moduleName"`
	ModuleVersion string `json:"moduleVersion"`
}

type GetPackagesResp struct {
	PackageList  []string `json:"packageList"`
	PackageCount uint     `json:"packageCount"`
}

type GoFileItem struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
}

type GetGoFilesResp struct {
	GoFileList  []*GoFileItem `json:"goFileList"`
	GoFileCount uint          `json:"goFileCount"`
}

type PongResp struct {
	Result string `json:"result"`
}
