// Code generated by goctl. DO NOT EDIT.
package types

type CommonDirReq struct {
	Dir string `form:"dir"`
}

type GetModulePathResp struct {
	ModulePath string `json:"modulePath"`
}

type GetProjectInfoReq struct {
	Dir        string `form:"dir"`
	ModulePath string `form:"modulePath"`
}

type GetProjectInfoResp struct {
	ModuleName   string   `json:"moduleName"`
	PackageList  []string `json:"packageList"`
	PackageCount uint     `json:"packageCount"`
}

type GenerateGraphResp struct {
	PackageCount uint `json:"packageCount"`
}
